title: "Single cell sequencing project"
subtitle: "Indrop-Flow pipeline"
intro_text: False

custom_logo: '/software/bi/biocore_tools/logo/biocore-logo.png'
custom_logo_url: 'https://biocore.crg.eu'
custom_logo_title: 'Bioinformatics Core Facility @ CRG'

extra_fn_clean_exts:
    - type: remove
      pattern: .fastq.gz.tagged
      
table_columns_visible:
    decimalPoint_format: '.'
    thousandsSep_format: ','
    FastQC (tagged):
        percent_duplicates: False
        percent_gc: False
        total_sequences: False
        
module_order:
 - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*_fastqc.zip'
 - fastqc:
        name: 'FastQC (tagged)'
        info: 'This section of the report shows FastQC results after quality trimming and tagging. Only the informative pairs are reported (in multiple files)'
        target: ''
        path_filters:
            - '*.tagged*_fastqc.zip'
 - star
  
